/*
 * ============================================================================
 * RISC-V SoC Verilator Testbench (main.cpp)
 * ============================================================================
 * * HOW TO COMPILE AND RUN:
 * * 1. Generate the C++ model and Makefile using Verilator:
 * verilator --cc --exe --trace-fst -Wall \
 * -I/workspaces/nano-rv32i/rtl/interfaces \
 * -I/workspaces/nano-rv32i/rtl/utils \
 * -I/workspaces/nano-rv32i/rtl/rv32i_core \
 * -I/workspaces/nano-rv32i/rtl/peripherals \
 * -I/workspaces/nano-rv32i/rtl/SoC \
 * /workspaces/nano-rv32i/rtl/SoC/soc_top.sv \
 * main.cpp
 * * 2. Compile the generated C++ code into an executable:
 * make -C obj_dir -j$(nproc) -f Vsoc_top.mk
 * * 3. Run the simulation:
 * ./obj_dir/Vsoc_top
 * * ============================================================================
 */

#include <iostream>
#include <memory>

// Include the Verilator API
#include <verilated.h>
// Include the FST tracing API (Fast Signal Trace)
#include <verilated_fst_c.h>

// Include the C++ class generated by Verilator representing your SoC
#include "Vsoc_top.h"

int main(int argc, char** argv) {
    // 1. Initialize Verilator internal arguments
    Verilated::commandArgs(argc, argv);
    
    // 2. Enable waveform tracing globally in Verilator
    Verilated::traceEverOn(true);

    // 3. Instantiate the actual CPU model
    // Using a smart pointer here ensures the memory is cleaned up safely at the end
    std::unique_ptr<Vsoc_top> top(new Vsoc_top);

    // 4. Setup the FST waveform dumper
    std::unique_ptr<VerilatedFstC> tfp(new VerilatedFstC);
    
    // Tell the dumper to trace up to 99 levels deep into the hierarchy of the SoC
    top->trace(tfp.get(), 99);
    
    // Open the output file
    tfp->open("sim_trace.fst");

    // 5. Setup Simulation Time and Limits
    uint64_t sim_time = 0;          // Absolute simulation time (half-cycles)
    const uint64_t MAX_TIME = 2000; // Run for 1000 full clock cycles

    // 6. Initialize CPU Inputs
    top->clk_27MHz = 0;
    top->reset_button = 1; // Hold the reset button down initially

    std::cout << "Starting Simulation..." << std::endl;

    // 7. The Main Simulation Loop
    // Runs until the simulation finishes natively OR we hit our MAX_TIME limit
    while (!Verilated::gotFinish() && sim_time < MAX_TIME) {
        
        // A. Toggle the clock every time the loop runs (sim_time advances)
        top->clk_27MHz = !top->clk_27MHz;

        // B. Release the reset button after 10 half-cycles (5 full clock cycles)
        if (sim_time > 10) {
            top->reset_button = 0; 
        }

        // C. Evaluate the SystemVerilog logic for this specific time step
        // This is where Verilator actually calculates all your combinations and flip-flops
        top->eval();

        // D. Dump the current state of every wire to the FST file
        tfp->dump(sim_time);

        // E. Step time forward
        sim_time++;
    }

    // 8. Cleanup and Exit
    // Verilator needs a final eval to wrap up any lingering $finish tasks
    top->final();
    tfp->close();

    std::cout << "Simulation completed successfully!" << std::endl;
    std::cout << "Waveform saved to: sim_trace.fst" << std::endl;

    return 0;
}