#!/usr/bin/bash

set -e

echo -e "\n\n\n======YOSYS SYNTHESIS======\n\n\n" > $NANO_ROOT/synth-log.txt
echo -e "\n\n\n======YOSYS SYNTHESIS======\n\n\n"

yosys -p "read_verilog -sv $NANO_ROOT/rtl/*.sv; synth_gowin -top datapath -json $NANO_ROOT/core.json" &>> $NANO_ROOT/synth-log.txt

echo -e "\n\n\n======NEXTPNR PLACE-AND-ROUTE======\n\n\n" >> $NANO_ROOT/synth-log.txt
echo -e "\n\n\n======NEXTPNR PLACE-AND-ROUTE======\n\n\n"

nextpnr-himbaechel --json $NANO_ROOT/core.json \
                   --write $NANO_ROOT/routed.json \
                   --device GW2AR-LV18QN88C8/I7 \
                   --vopt family=GW2A-18C \
                   --vopt cst=$NANO_ROOT/nano20k.cst &>> $NANO_ROOT/synth-log.txt

echo -e "\n\n\n=======PROJECT APICULA BITSTREAM GENERATION======\n\n\n" >> $NANO_ROOT/synth-log.txt
echo -e "\n\n\n=======PROJECT APICULA BITSTREAM GENERATION======\n\n\n"

gowin_pack -d GW2A-18C -o $NANO_ROOT/firmware.fs $NANO_ROOT/routed.json &>> $NANO_ROOT/synth-log.txt

echo -e "\n\nAll Done!" >> $NANO_ROOT/synth-log.txt
echo -e "\n\nAll done!"