name: RISC-V CI

on:
  push:
  pull_request:

jobs:
  test-in-codespace-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEVCONTAINER_PUSH_PULL }}

      - name: Run Tests in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/nano-rv32i-env
          push: always
          runCmd: |
            set -e
            setup-basic
            lint
            synthesize
            test-dynamic

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codespace-test-logs
          path: logs/