name: RISC-V Formal Verification

on:
  push:
  pull_request:

jobs:
  formal-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Formal Verification in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            source ~/.bashrc
            test-formal

      - name: Upload Formal Logs
        if: always() # Ensures logs are uploaded even if formal checks fail
        uses: actions/upload-artifact@v4
        with:
          name: formal-verification-logs
          path: logs/