name: RISC-V Formal Verification

on:
  push:
  pull_request:

jobs:
  formal-verification:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Formal Verification in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          # Define the registry and image name dynamically
          imageName: ghcr.io/${{ github.repository }}/nano-rv32i-env
          
          # Use the registry image as a cache to skip rebuilding
          cacheFrom: ghcr.io/${{ github.repository }}/nano-rv32i-env
          
          # Always push the newly built image back to the registry
          push: always
          runCmd: |
            setup-basic
            test-formal

      - name: Upload Formal Logs
        if: always() # Ensures logs are uploaded even if formal checks fail
        uses: actions/upload-artifact@v4
        with:
          name: formal-verification-logs
          path: logs/